### ISSUE TITLE
CI: Run tutorials against other kornia versions

### ISSUE THREAD

**Issue by johnnv1** [kornia/tutorials#84]
With the new CI setup (#81) we can choose against which kornia version runs the tutorials. By using the git reference to the `env` action.

Example
```yaml
    uses: kornia/workflows/.github/workflows/tutorials.yml@v1.4.1
    with:
      ref: 'main' # Or any git reference, tag, commit, etc -- so can be v0.7.0, etc
```

> This `ref` input is the git reference of kornia/kornia repository.

The problem with it now, is that not all tutorials will work on older kornia versions, so this needs to be dealt with somehow
